apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: siphon-brukernotifikasjoner
  namespace: min-side
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 34.88.76.52/32
  podSelector:
    matchLabels:
      app: tms-varsel-siphon-sql-proxy
  policyTypes:
    - Egress
