apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tms-varsel-siphon-sql-proxy
  namespace: min-side
  labels:
    team: min-side
spec:
  image: gcr.io/cloudsql-docker/gce-proxy:1.29.0-alpine
  command:
    - /cloud_sql_proxy
    - -term_timeout=30s
    - -instances=min-side-dev-911f:europe-north1:brukernotifikasjon-cache=tcp:0.0.0.0:5432
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 32Mi
  service:
    port: 5432
    protocol: tcp
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  accessPolicy:
    inbound:
      rules:
        - application: tms-varsel-siphon
