apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-varsel-siphon
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-varsel-siphon-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "50m"
      memory: 128Mi
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tms-varsel-authority
    outbound:
      rules:
        - application: tms-varsel-siphon-sql-proxy
