apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: siphon-brukernotifikasjoner
  namespace: min-side
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 35.228.205.73/32
  podSelector:
    matchLabels:
      app: tms-varsel-siphon
  policyTypes:
    - Egress
